avalibleTimes = [
    {
        "id":"0",
        "time":"08:00",
        "reserved":false,
        "userId":""
    },
    {
        "id":"1",
        "time":"08:30",
        "reserved":false,
        "userId":""
    },
    {
        "id":"2",
        "time":"09:00",
        "reserved":false,
        "userId":""
    },
    {
        "id":"3",
        "time":"09:30",
        "reserved":false,
        "userId":""
    },
    {
        "id":"4",
        "time":"10:00",
        "reserved":false,
        "userId":""
    },
    {
        "id":"5",
        "time":"10:30",
        "reserved":false,
        "userId":""
    },
    {
        "id":"6",
        "time":"11:00",
        "reserved":false,
        "userId":""
    },
    {
        "id":"7",
        "time":"11:30",
        "reserved":false,
        "userId":""
    },
    {
        "id":"8",
        "time":"12:00",
        "reserved":false,
        "userId":""
    },
    {
        "id":"9",
        "time":"12:30",
        "reserved":false,
        "userId":""
    },
    {
        "id":"10",
        "time":"13:00",
        "reserved":false,
        "userId":""
    },
    {
        "id":"11",
        "time":"13:30",
        "reserved":false,
        "userId":""
    },
    {
        "id":"12",
        "time":"14:00",
        "reserved":false,
        "userId":""
    },
    {
        "id":"13",
        "time":"14:30",
        "reserved":false,
        "userId":""
    },
    {
        "id":"14",
        "time":"15:00",
        "reserved":false,
        "userId":""
    },
    {
        "id":"15",
        "time":"15:30",
        "reserved":false,
        "userId":""
    },
    {
        "id":"16",
        "time":"16:00",
        "reserved":false,
        "userId":""
    },
    {
        "id":"17",
        "time":"16:30",
        "reserved":false,
        "userId":""
    },
    {
        "id":"18",
        "time":"17:00",
        "reserved":false,
        "userId":""
    },
    {
        "id":"19",
        "time":"17:30",
        "reserved":false,
        "userId":""
    },
    {
        "id":"20",
        "time":"18:00",
        "reserved":false,
        "userId":""
    },
    {
        "id":"21",
        "time":"18:30",
        "reserved":false,
        "userId":""
    },
    {
        "id":"22",
        "time":"19:00",
        "reserved":false,
        "userId":""
    },
    {
        "id":"23",
        "time":"19:30",
        "reserved":false,
        "userId":""
    },
    {
        "id":"24",
        "time":"20:00",
        "reserved":false,
        "userId":""
    }
]