let usuariosDB = 
[
    {
        id:12341,
        firstName:"Jonatan",
        lastName:"Merlo",
        email:"unEmail@email.com",
        userName:"Jony123",
        userPassword:"12341"
    },
    {
        id:41231,
        firstName:"Jonatan2",
        lastName:"Merlo2",
        email:"otroEmail@email.com",
        userName:"Jony213",
        userPassword:"4231"
    }
]